site_name: Documentação

nav:
  - Integrantes: enunciado.md
  - TLS: index.md
  - Keycloak: keycloak.md
  - Mensal 2 - Infraestrutura Segura e Automatizada: mensal2.md

theme:
  name: material
  language: pt-BR
  logo: llw.ico
  favicon: llw.ico
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Modo escuro
plugins:
  - search
extra:
  generator: false

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
      
copyright: '© 2025 LionLaw - LLW'
